### ISSUE TITLE
Loading animation length

### ISSUE THREAD

**Issue by gibbletz** [LTVFD/LTVFD_Website#4]
Loading animation takes too long for me, and if that is the case then normal users will be very impatient. If it is a set time it need to be shortened. If it's an issue with how long it take to load elements tell me I'm an idiot and I'll improve the server.

**Comment by TicklishGiraffe** [comment]
I'm not sure what it is exactly.  I think it might be just the loading of the elements because its gotten slower over time as we have added stuff.  Once its loaded it seems to go just fine, even with reloading it. Is it possibly due to the fact the server is running two websites at once technically?

**Comment by TicklishGiraffe** [comment]
I've tested this us a bunch and cleared my cache several times, doesn't seem to be an issue so far on my work computer, home computer, and mobile.  Going to close this issue for now but feel free to re-open it if it re occurs.
